app/views/estudiante/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

urlpatterns = [
  path('solicitudes/', ListarSolicitudes.as_view(), name='listar_solicitudes'),
  path('solicitudes/<int:pk>/', VisualizarSolicitud.as_view(), name='visualizar_solicitud'),
  path('solicitudes/crear_solicitud/', CrearSolicitud.as_view(), name='crear_solicitud'),
  path('solicitudes/modificar_solicitud/<int:pk>/', ModificarSolicitud.as_view(), name='modificar_solicitud'),
  path('solicitudes/eliminar_solicitud/<int:pk>/', EliminarSolicitud.as_view(), name='eliminar_solicitud'),
  path('notificaciones/', ListarNotificaciones.as_view(), name='listar_notificaciones_estudiante'),
  path('notificaciones/<int:pk>/', VisualizarNotificacion.as_view(), name='visualizar_notificacion_estudiante'),
  path('notificaciones/eliminar_notificacion/<int:pk>/', EliminarNotificacion.as_view(), name='eliminar_notificacion_estudiante'),
]

app/views/secretario/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

urlpatterns = [
  path('estudiantes/', ListarEstudiantes.as_view(), name='listar_estudiantes'),
  path('estudiantes/<int:pk>/', VisualizarEstudiante.as_view(), name='visualizar_estudiante'),
  path('estudiantes/crear_estudiante/', CrearEstudiante.as_view(), name='crear_estudiante'),
  path('estudiantes/modificar_estudiante/<int:pk>/', ModificarEstudiante.as_view(), name='modificar_estudiante'),
  path('estudiantes/eliminar_estudiante/<int:pk>/', EliminarEstudiante.as_view(), name='eliminar_estudiante'),
  path('reportes/', ListarReportes.as_view(), name='listar_reportes'),
  path('reportes/<int:pk>/', VisuzalizarReporte.as_view(), name='visualizar_reporte'),
  path('reportes/crear_reporte/', CrearReporte.as_view(), name='crear_reporte'),
  path('reportes/eliminar_reporte/<int:pk>/', EliminarReporte.as_view(), name='eliminar_reporte'),
  path('solicitudes/', ListarSolicitudes.as_view(), name='listar_solicitudes_secretario'),
  path('solicitudes/<int:pk>/', VisualizarSolicitud.as_view(), name='visualizar_solicitud_secretario'), 
  path('notificaciones/', ListarNotificaciones.as_view(), name='listar_notificaciones_secretario'),
  path('notificaciones/<int:pk>/', VisualizarNotificacion.as_view(), name='visualizar_notificacion_secretario'),
  path('notificaciones/eliminar_notificacion/<int:pk>/', EliminarNotificacion.as_view(), name='eliminar_notificacion_secretario'),
]

tramites_docentes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.views.autenticar.urls')),
    path('estudiante/', include('app.views.estudiante.urls')),
    path('secretario/', include('app.views.secretario.urls')),
    path('decano/', include('app.views.decano.urls')),
]

app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

class Usuario(models.Model):
  usuario = models.OneToOneField(User, on_delete = models.CASCADE, primary_key = 1)
  rol = models.CharField(max_length = 20, blank = 0, null = 0)

  class Meta:
    verbose_name = 'Usuario'
    verbose_name_plural = 'Usuarios'
    db_table = 'usuario'


class Estudiante(Usuario):
  grupo = models.CharField(max_length = 20, null = 0, blank = 0)
  anno = models.IntegerField(default = 1)
  
  class Meta:
    verbose_name = 'Estudiante'
    verbose_name_plural = 'Estudiantes'
    db_table = 'estudiantes'
  
  
class Solicitud(models.Model):
  tipo_opciones = [
    ('Baja', 'Baja'),
    ('Continuidad de Estudios', 'Continuidad de Estudios'),
    ('Licencia', 'Licencia'),
    ('Traslado', 'Traslado'),
    ]
  estado_opciones = [
    ('Aprobado','Aprobado'),
    ('Denegado','Denegado'),
  ]
  tipo = models.CharField(max_length = 255, null = 0, blank = 0, choices = tipo_opciones, default = 'Baja')
  motivo = models.TextField(blank = 0, null = 0)
  fecha = models.DateField(default = timezone.now)
  estado = models.CharField(max_length = 50, choices = estado_opciones, default = 'Pendiente')
  estudiante = models.ForeignKey(Estudiante, on_delete = models.CASCADE)
  
  class Meta:
    verbose_name = 'Solicitud'
    verbose_name_plural = 'Solicitudes'
    db_table = 'solicitudes'
  

class Reporte(models.Model):
  bajas = models.IntegerField()
  continuidad = models.IntegerField()
  licencias = models.IntegerField()
  traslados = models.IntegerField()
  bajas_aprobadas = models.IntegerField()
  continuidad_aprobados = models.IntegerField()
  licencias_aprobadas = models.IntegerField()
  traslados_aprobados = models.IntegerField()
  fecha = models.DateTimeField(default = timezone.now)
  
  class Meta:
    verbose_name = 'Reporte'
    verbose_name_plural = 'Reportes'
    db_table = 'reportes'
  

class NotificacionSolicitud(models.Model):
  estudiante = models.ForeignKey(Estudiante, on_delete = models.CASCADE) 
  tipo = models.CharField(max_length = 255, null = 0, blank = 0)
  motivo = models.TextField(blank = 0, null = 0)
  estado = models.CharField(max_length = 50, blank = 0, null = 0)
  fecha = models.DateField()
  fecha_notificacion = models.DateField(default = timezone.now)
  visto = models.BooleanField(default=0)
  
  class Meta:
    verbose_name = 'Notificacion'
    verbose_name_plural = 'Notifiaciones'
    db_table = 'notificaciones'
  
class NotificacionSolicitudEstudiante(NotificacionSolicitud):
  class Meta:
    verbose_name = 'NotificacionEstudiante'
    verbose_name_plural = 'NotifiacionesEstudiante'
    db_table = 'notificaciones_estudiante'

class NotificacionSolicitudSecretario(NotificacionSolicitud):
  class Meta:
    verbose_name = 'NotificacionSecretario'
    verbose_name_plural = 'NotifiacionesSecretario'
    db_table = 'notificaciones_secretario'

  

app/views/estudiante/views.py
from django.views.generic import CreateView, UpdateView, DeleteView, DetailView, ListView
from django.urls import reverse_lazy
from app.models import Solicitud, NotificacionSolicitudEstudiante
from app.forms import SolicitudForm

class ListarSolicitudes(ListView):
  rol = 'estudiante'
  model = Solicitud
  template_name = 'estudiante/solicitudes/listar_solicitudes.html'
  
  def get_queryset(self):
      return Solicitud.objects.filter(estudiante = self.request.user.usuario.estudiante).order_by('-fecha')
  
    
class VisualizarSolicitud(DetailView):
  rol = 'estudiante'
  model = Solicitud
  template_name = 'estudiante/solicitudes/visualizar_solicitud.html'
  context_object_name = 'solicitud'

class CrearSolicitud(CreateView):
  rol = 'estudiante'
  model = Solicitud
  form_class = SolicitudForm
  template_name = 'estudiante/solicitudes/crear_solicitud.html'
  success_url = reverse_lazy('listar_solicitudes')
  
  def get_context_data(self, **kwargs):
    ctx = super().get_context_data(**kwargs)
    ctx['crear'] = 1
    return ctx
  
  def form_valid(self, form):
     form.instance.estudiante = self.request.user.usuario.estudiante
     return super().form_valid(form)

class ModificarSolicitud(UpdateView):
  rol = 'estudiante'
  model = Solicitud
  form_class = SolicitudForm
  template_name = 'estudiante/solicitudes/crear_solicitud.html'
  success_url = reverse_lazy('listar_solicitudes')
  
  
class EliminarSolicitud(DeleteView):
  rol = 'estudiante'
  model = Solicitud
  template_name = 'layout/eliminar.html'
  success_url = reverse_lazy('listar_solicitudes')
  
  def get_context_data(self, **kwargs):
    ctx = super().get_context_data(**kwargs)
    ctx['mensaje'] = '¿Seguro que desea eliminar esta solicitud?'
    return ctx
  

class ListarNotificaciones(ListView):
  rol = 'estudiante'
  model = NotificacionSolicitudEstudiante
  template_name = 'estudiante/notificaciones/listar_notificaciones.html'
  
  def get_queryset(self):
    return NotificacionSolicitudEstudiante.objects.filter(estudiante = self.request.user.usuario.estudiante).order_by('visto')
  

class VisualizarNotificacion(DetailView):
  rol = 'estudiante'
  model = NotificacionSolicitudEstudiante
  context_object_name = 'notificacion'
  template_name = 'estudiante/notificaciones/visualizar_notificacion.html'
  
  def dispatch(self, request, *args, **kwargs):
    a = self.get_object()
    a.visto = True
    a.save()
    return super().dispatch(request, *args, **kwargs)
  

class EliminarNotificacion(DeleteView):
  rol = 'estudiante'
  model = NotificacionSolicitudEstudiante
  template_name = 'layout/eliminar.html'
  success_url = reverse_lazy('listar_notificaciones_estudiante')
  
  def get_context_data(self, **kwargs):
    ctx = super().get_context_data(**kwargs)
    ctx['mensaje'] = '¿Seguro que desea eliminar la notificación?'
    return ctx

app/views/secretario/views.py
from django.db.models.query import QuerySet
from django.http import HttpRequest
from django.views.generic import ListView, DetailView, DeleteView, View
from app.models import Estudiante, User, Reporte, Solicitud, NotificacionSolicitudSecretario
from app.forms import EstudianteForm
from django.shortcuts import render, redirect
from django.urls import reverse_lazy

class ListarEstudiantes(ListView):
  rol = 'secretario'
  model = Estudiante
  template_name = 'secretario/estudiantes/listar_estudiantes.html'
  
  def get_queryset(self):
    return Estudiante.objects.all().order_by('usuario__first_name')


class VisualizarEstudiante(DetailView):
  rol = 'secretario'
  model = Estudiante
  template_name = 'secretario/estudiantes/visualizar_estudiante.html'
  context_object_name = 'estudiante'

class CrearEstudiante(View):
  rol = 'secretario'
  def post(self, request, *args, **kwargs):
    form = EstudianteForm(request.POST)
    if form.is_valid():
      try:
        usuario = User.objects.create(
        username = form.cleaned_data['nombre_usuario'], 
        password = form.cleaned_data['password'], 
        first_name = form.cleaned_data['nombre'], 
        last_name = form.cleaned_data['apellidos'])
        Estudiante.objects.create(
          usuario = usuario,
          rol = 'estudiante',
          grupo = form.cleaned_data['grupo'],
          anno = form.cleaned_data['anno']
        )
        return redirect('listar_estudiantes')
      except:
        ctx = {
          'crear' : 1,
          'form':form,
          'error':'Ya existe un usuario con el nombre de usuario insertado.',
          }
        return render(request, 'secretario/estudiantes/crear_estudiante.html', ctx)
  
  def get(self, request, *args, **kwargs):
    return render(request, 'secretario/estudiantes/crear_estudiante.html', {'crear' : 1,'form':EstudianteForm()})
  

class ModificarEstudiante(View):
  rol = 'secretario'
  def post(self, request, *args, **kwargs):
    estudiante = Estudiante.objects.get(pk=kwargs.get('pk'))
    form = EstudianteForm(request.POST)
    if form.is_valid():
      try:
        estudiante.usuario.username = form.cleaned_data['nombre_usuario']
        estudiante.usuario.password = form.cleaned_data['password']
        estudiante.usuario.first_name = form.cleaned_data['nombre'] 
        estudiante.usuario.last_name = form.cleaned_data['apellidos']
        estudiante.grupo = form.cleaned_data['grupo']
        estudiante.anno = form.cleaned_data['anno']
        estudiante.usuario.save()
        estudiante.save()
        return redirect('listar_estudiantes')
      except:
        ctx = {
          'form':form,
          'error':'Ya existe un usuario con el nombre de usuario insertado.',
          }
        return render(request, 'secretario/estudiantes/crear_estudiante.html', ctx)
  
  def get(self, request, *args, **kwargs):
    estudiante = Estudiante.objects.get(pk=kwargs.get('pk'))
    form = EstudianteForm(initial={
      'nombre_usuario': estudiante.usuario.username,
      'password': estudiante.usuario.password,
      'nombre' : estudiante.usuario.first_name,
      'apellidos' : estudiante.usuario.last_name,
      'grupo' : estudiante.grupo,
      'anno' : estudiante.anno
    }) 
    return render(request, 'secretario/estudiantes/crear_estudiante.html', {'form':form})
  

class EliminarEstudiante(DeleteView):
  rol = 'secretario'
  model = User
  template_name = 'layout/eliminar.html'
  success_url = reverse_lazy('listar_estudiantes')
  
  def get_context_data(self, **kwargs):
    ctx = super().get_context_data(**kwargs)
    ctx['mensaje'] = '¿Seguro que desea eliminar este estudiante?'
    return ctx
  

class ListarReportes(ListView):
  rol = 'secretario'
  model = Reporte 
  template_name = 'secretario/reportes/listar_reportes.html'
  
  
class VisuzalizarReporte(DetailView):
  rol = 'secretario'
  model = Reporte
  template_name = 'secretario/reportes/visualizar_reporte.html'
  context_object_name = 'reporte'
  

class EliminarReporte(DeleteView):
  rol = 'secretario'
  model = Reporte
  template_name = 'layout/eliminar.html'
  success_url = reverse_lazy('listar_reportes')
  
  def get_context_data(self, **kwargs):
    ctx = super().get_context_data(**kwargs)
    ctx['mensaje'] = "¿Seguro que desea eliminar este reporte?"
    return ctx


class CrearReporte(View):
  rol = 'secretario'
  def setup(self, request: HttpRequest, *args, **kwargs):
    self.bajas = Solicitud.objects.filter(tipo = 'Baja').count()
    self.continuidad = Solicitud.objects.filter(tipo = 'Continuidad de Estudios').count()
    self.licencias = Solicitud.objects.filter(tipo = 'Licencia').count()
    self.traslados = Solicitud.objects.filter(tipo = 'Traslado').count()
    self.bajas_aprobadas = Solicitud.objects.filter(tipo = 'Baja', estado = 'aprobada').count()
    self.continuidad_aprobados = Solicitud.objects.filter(tipo = 'Continuidad de Estudios', estado = 'aprobada').count()
    self.licencias_aprobadas = Solicitud.objects.filter(tipo = 'Licencia', estado = 'aprobada').count()
    self.traslados_aprobados = Solicitud.objects.filter(tipo = 'Traslado', estado = 'aprobada').count()
    return super().setup(request, *args, **kwargs)
  
  def get(self, request, *args, **kwargs): 
    datos = {
      'bajas' : self.bajas,
      'continuidad' : self.continuidad,
      'licencias' : self.licencias,
      'traslados' : self.traslados,
      'bajas_aprobadas' : self.bajas_aprobadas,
      'continuidad_aprobados' : self.continuidad_aprobados,
      'licencias_aprobadas' : self.licencias_aprobadas,
      'traslados_aprobados' : self.traslados_aprobados,
    }
    return render(request, 'secretario/reportes/crear_reporte.html', datos)
  
  def post(self, request, *args, **kwargs):
    Reporte.objects.create(
      bajas = self.bajas,
      continuidad = self.continuidad,
      licencias = self.licencias,
      traslados = self.traslados,
      bajas_aprobadas = self.bajas_aprobadas,
      continuidad_aprobados = self.continuidad_aprobados,
      licencias_aprobadas = self.licencias_aprobadas,
      traslados_aprobados = self.traslados_aprobados
    )
    return redirect('listar_reportes')


class ListarSolicitudes(ListView):
  rol = 'secretario'
  model = Solicitud
  template_name = 'secretario/solicitudes/listar_solicitudes.html'


class VisualizarSolicitud(DetailView):
  rol = 'secretario'
  model = Solicitud
  template_name = 'secretario/solicitudes/visualizar_solicitud.html'
  
  
class ListarNotificaciones(ListView):
  rol = 'secretario'
  model = NotificacionSolicitudSecretario
  template_name = 'secretario/notificaciones/listar_notificaciones.html'
  
  def get_queryset(self):
    return NotificacionSolicitudSecretario.objects.all().order_by('visto')

class VisualizarNotificacion(DetailView):
  rol = 'secretario'
  model = NotificacionSolicitudSecretario
  context_object_name = 'notificacion'
  template_name = 'secretario/notificaciones/visualizar_notificacion.html'
  
  def dispatch(self, request, *args, **kwargs):
    a = self.get_object()
    a.visto = True
    a.save()
    return super().dispatch(request, *args, **kwargs)
  
  
class EliminarNotificacion(DeleteView):
  rol = 'secretario'
  model = NotificacionSolicitudSecretario
  template_name = 'layout/eliminar.html'
  success_url = reverse_lazy('listar_notificaciones_secretario')
  
  def get_context_data(self, **kwargs):
    ctx = super().get_context_data(**kwargs)
    ctx['mensaje'] = '¿Seguro que desea eliminar la notificación?'
    return ctx

templates/secretario/estudiantes/crear_estudiante.html
{% extends "layout/base_secretario.html" %}

{% block 'contenido' %}
<div class="text-center mt-3">
  {% if crear %}
  <h1>Insertar Nuevo Estudiante</b></h1>
  {% else %}
  <h1>Modificar Datos del Estudiante</b></h1>
  {% endif %}
</div>
<hr>
<div class="container">
  <form method='post' id="form">
    {% csrf_token %}
    <div class="row mb-3">
      <div class="col-sm-4">
        <label for="nombre" class='form-label'>Nombre:</label>
        {{form.nombre}}
      </div>
      <div class="col-sm-8">
        <label for="apellidos" class='form-label'>Apellidos:</label>
        {{form.apellidos}}
      </div>
    </div>
    <div class="row">
      <div class="col-sm-3">
        <label for="nombre_usuario" class='form-label'>Usuario:</label>
        {{form.nombre_usuario}}
      </div>
      <div class="col-sm-3">
        <label for="password" class='form-label'>Contraseña:</label>
        {{form.password}}
      </div>
      <div class="col-sm-3">
        <label for="grupo" class='form-label'>Grupo:</label>
        {{form.grupo}}
      </div>
      <div class="col-sm-3">
        <label for="anno" class='form-label'>Año Docente:</label>
        {{form.anno}}
      </div>
    </div>
  </form>
  {% if error %}
  <div class="alert alert-danger d-flex align-items-center alert-dismissible mt-3" role="alert">
    {{error}}
    <button class="btn-close" data-bs-dismiss="alert" aria-label="close"></button>
  </div>
  {% endif %}
  <div class="mt-5 p-4"></div>
  <div class="fixed-bottom d-flex p-3 justify-content-around bg-white border shadow">
    <button class="btn btn-danger" type="button" data-bs-toggle="modal" data-bs-target="#cancelar">Cancelar</button>
    <button class="btn btn-success" type="button" data-bs-toggle="modal" data-bs-target="#aceptar">Aceptar</button>
  </div>
  <div class="modal" id="cancelar">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Descartar Cambios</h5>
          <button data-bs-dismiss="modal" class="btn-close"></button>
        </div>
        <div class="modal-body">
          <p>¿Seguro que desea descartar los cambios actuales?</p>
        </div>
        <div class="modal-footer d-flex justify-content-between">
          <button data-bs-dismiss="modal" class="btn btn-danger" type="button">Cancelar</button>
          <a href="{% url 'listar_estudiantes' %}" class="btn btn-success">Aceptar</a>
        </div>
      </div>
    </div>
  </div>
  <div class="modal" id="aceptar">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Confirmar Cambios</h5>
          <button data-bs-dismiss="modal" class="btn-close"></button>
        </div>
        <div class="modal-body">
          <p>¿Desea guardar los cambios?</p>
        </div>
        <div class="modal-footer d-flex justify-content-between">
          <button data-bs-dismiss="modal" class="btn btn-danger" type="button">Cancelar</button>
          <button data-bs-dismiss="modal" class="btn btn-success" type="submit" form="form">Aceptar</button>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/secretario/estudiantes/listar_estudiantes.html
{% extends "layout/base_secretario.html" %}
{% load static %}

{% block 'sub-estilos' %}
<link rel="stylesheet" href="{% static 'css/secretario/lista.css' %}">
{% endblock %}

{% block 'contenido' %}
  <div class="fixed-bottom d-flex p-3 justify-content-center bg-white border shadow">
    <a href="{% url 'crear_estudiante' %}" class="btn btn-secretario">Nuevo Estudiante</a>
  </div>
  <div class='text-center mt-3 user-select-none'>
    <h1>Estudiantes</h1>
  </div>
  <hr>
  <div class="container">
    <div class='lista'>
      {% for estudiante in object_list %}
      <div class="lista-item">
        <a class="lista-item-link" href="{% url 'visualizar_estudiante' estudiante.pk %}"
        style="font-size: 20px;">
        <b>Grupo {{estudiante.grupo}}:</b> 
        {{estudiante.usuario.first_name}}
        {{estudiante.usuario.last_name}}
      </a>
      <a href="{% url 'modificar_estudiante' estudiante.pk %}" class="lista-item-btn btn-modificar">M</a>
      <a href="{% url 'eliminar_estudiante' estudiante.pk %}" class="lista-item-btn btn-eliminar">E</a>
      </div>
      {% endfor %}
    </div>
    <div class="mt-5 p-4"></div>
  </div>
{% endblock %}

templates/secretario/estudiantes/visualizar_estudiante.html
{% extends "layout/base_secretario.html" %}
{% load static %}

{% block 'sub-estilos' %}
<link rel="stylesheet" href="{% static 'css/botones.css' %}">
{% endblock %}

{% block 'titulo' %}Visualizar Estudiante{% endblock %}

{% block 'contenido' %}
<div class="text-center mt-3">
  <h1>Visualizar Datos del Estudiante</h1>
</div>
<hr>
<div class="container p-4">
  <div class="list-group">
    <div class="list-group-item">
      <span class='fw-bold'>Nombre:</span>
      <span>
        {{estudiante.usuario.first_name}}
        {{estudiante.usuario.last_name}}
      </span>
    </div>
    <div class="list-group-item">
      <span class='fw-bold'>Nombre de Usuario:</span>
      <span>
        {{estudiante.usuario.username}}
      </span>
    </div>
    <div class="list-group-item">
      <span class='fw-bold'>Grupo:</span>
      <span>
        {{estudiante.grupo}}
      </span>
    </div>
    <div class="list-group-item">
      <span class='fw-bold'>Año Docente:</span>
      <span>
        {{estudiante.anno}}
      </span>
    </div>
    <div class="list-group-item">
      <span class='fw-bold'>Cantidad de Solicitudes:</span>
      <span>
        {{estudiante.solicitud_set.all.count}}
      </span>
    </div>
  </div>
</div>
<div class="mt-5 p-4"></div>
<div class="fixed-bottom d-flex p-3 justify-content-around bg-white border shadow">
  <a href="{% url 'modificar_estudiante' estudiante.pk %}" class="btn btn-modificar">Modificar Estudiante</a>
  <a href="{% url 'eliminar_estudiante' estudiante.pk %}" class="btn btn-eliminar">Eliminar Estudiante</a>
</div>
{% endblock %}